genuinetools/img

README.md, main.go, worker/runc/workeropt.go
`naive` is the safest and maybe a good candidate for the default.
I'll open a buildkit PR to deduplicate the worker code across the both projects later (probably next week)
=> new backend: naive

fsutils/diff.go
See upstream bug fix https://github.com/containerd/continuity/pull/103
This had an effect on buildkit output. I don't mind exporting some of these types of functions if you want to use them directly. Continuity is meant to be more general purpose fs utility package so we can add stuff there are specifically for build use cases (we would like to merge Tonis' fsutil package as well).
=> fsutils: ensure rmdir gets set for every directory

README.md
This typo was introduced via https://github.com/jessfraz/img/commit/c61a8e42f5cb3892837d2de02d2d74b254433411#commitcomment-27712251 , which I unexpectedly committed directly without opening a PR (sorry :sweat_smile: )
=> Fix my typo

README.md
/proc/sys/kernel/unprivileged_userns_clone was unintentionally typo'd to /proc/sys/kernel/unprivileged_ns_clone
=> Change path to userns_clone

login.go
Server param passed in on CLI was ignored and token retrieval was broken.
=> fix remote login

Makefile, README.md
This change will install img into /usr/local/sbin rather than $GOPATH/bin, which by default on most systems will be $HOME/go. This allows any user in the system (like root) access to the binary, as well as removing the extra step to re-compile `img` a second time (`go build && go install`).
This also removes the install step from `make all` due to the need for root privileges. Please let me know if you'd prefer to keep it as-is.
=> install img just like runc

login.go
Previously logic was reversed so the message was displayed only on non-default registries.
Add newline to the end of the message.
=> Show informational message on default registry

build_test.go, diff/mount/temp.go
If building an image with `scratch` base, `img` panics due to lack of lower mount:
```Dockerfile
FROM alpine
FROM scratch
COPY --from=0 / /
````
```console
$ img build -t scratchy .
Building scratchy:latest
Setting up the rootfs... this may take a bit.
INFO[0000] resolving docker.io/tonistiigi/copy@sha256:476e0a67a1e4650c6adaf213269a2913deb7c52cbc77f954026f769d51e1a14e
INFO[0000] resolving docker.io/library/alpine@sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b
INFO[0000] unpacking docker.io/library/alpine@sha256:7b848083f93822dd21b0a2f14a110bd99f6efb4b838d499df6d04a49d0debf8b
INFO[0001] unpacking docker.io/tonistiigi/copy@sha256:476e0a67a1e4650c6adaf213269a2913deb7c52cbc77f954026f769d51e1a14e
RUN [copy /src-0 /dest/]
--->
<--- nbypzzl5wqm5rmep5pppgeavk 0 <nil> …
```
=> Pass empty root to walker in case we have no lower mounts

client/list.go, list.go
Previously it didn't walk through the layers and displayed the size only of the top descriptor.
NB: size returned by `containerd/images.Image.Size()` (this PR) is less than displayed by docker. Though it kinda matches with image sizes on Docker Hub and from `img save`. There are likely multiple sizes in fact but I don't know. :)
UPD: okay it seems I figured this out: `img du` displays image size on disk which matches with docker.
=> Fix image size calculation in 'list' command

Dockerfile
There is no `github.com/genuinetools/runc` repo. And probably there shouldn't be one. I guess that this custiom `runc` dependency will be gone when `runc` patches will be merged upstream.
=> Fix runc repo location in Dockerfile

build.go
Hi @jessfraz, this just closes target files after write. Previously all target files were being held open for the entire context copy, and I was getting errors about too many open files. Thanks!
=> Don't leave all target files open when copying context from stdin

client/workeropt.go, executor/runc/executor.go
Previously it was failing with the following error:
$ img build -backend overlayfs -t foo /tmp/foo
...
--->
rootfs (/tmp/img/runc/overlayfs/executor/6d8kla6y1m19bfs064irjayj6/overlay) does not exist
<--- 6d8kla6y1m19bfs064irjayj6 1 <nil>
solving failed: executor failed running [/bin/sh -c echo hello]: exit code 1
=> support unprivileged overlayfs (on Ubuntu and some distros)

client/push.go, push.go
related to #85 
moby/buildkit already accept push to insecure registries.
this PR just add the flag to use it.
=> push: Add insecure-registry flag

executor/runc/executor.go
Implements Check that root is not symlink to fail early
https://github.com/jessfraz/img/blob/8e59455cdd12df371ec7babf2a883a656a5a39e1/executor/runc/executor.go#L50
=> Check that root is not symlink

.travis.yml, Makefile, README.md, contrib/e2e-dockerfiles-build-test.sh, internal/binutils/binutils.go, internal/binutils/install.go, internal/binutils/install_noembed.go, main.go
works like so:
```
$ make install BUILDTAGS="seccomp noembed"
+ install
go install -a -tags "seccomp noembed" -ldflags "-w -X github.com/genuinetools/img/version.GITCOMMIT=455629ae-dirty -X github.com/genuinetools/img/version.VERSION=v0.4.1" .
$ img build -t thing .
FATA[0000] Installing embedded runc binary failed: please install `runc`
```
closes #107
cc @AkihiroSuda
=> add noembed buildtag

README.md, main.go
* prevent `/tmp/img` from being removed on reboot
* should work with distros that mounts `/tmp` with incompatible options
Fix #97 
cc @frezbo
=> change default state dir from /tmp/img to /home/user/.local/share/img

README.md
Per #119, it's not possible to build with `go get`. Take that out of the README.md file so it's not tempting.
Closes #134
=> Remove "Via Go" from README, since it doesn't work (#119)

Gopkg.lock, login.go, vendor/github.com/genuinetools/reg/registry/authchallenge.go, vendor/github.com/genuinetools/reg/registry/authchallenge_test.go, vendor/github.com/genuinetools/reg/registry/tokentransport.go, vendor/github.com/genuinetools/reg/registry/tokentransport_test.go
This PR is structured as two commits:
- The first commit pulls in a new version of genuinetools/reg in order to pick up some recent changes to basic auth detection
- The second commit uses the changes pulled in from the first to detect registries that require basic auth (e.g. ECR) s.t. `img login` does not fail on these registries
I've tested these changes manually with an ECR repository and verified that pushes and pulls operate as expected. This addresses part of #128.
=>  Do not fail on basic auth in login.

README.md
Came across Arch install instructions and noticed it mentions pacman, which won't install AUR packages.
I included Arch build instructions for AUR helper of choice and also building with the PKGBUILD. 
Looking forward to digging into more of this, this project has huge promise for unprivileged Docker in Docker builds and I have already suggested to my DevOps evangelists to follow its development. :+1:
=> Updated Arch installation instructions 

README.md
I needed this library on Ubuntu to `make` the source 😄
=> Note `libseccomp-dev` required during install

README.md
Fix IMG_SHA256 to match v0.5.0 release
From https://github.com/genuinetools/img/releases/tag/v0.5.0
=> Fix IMG_SHA256 to match v0.5.0 release

reexec.go
Without this check img subcommands will fail:
nsenter: failed to execv: No such file or directory
nsenter: failed to sync with parent: SYNC_USERMAP_ACK: got 255: Success
nsenter: failed to use newuidmap: Success
With it, you get this instead:
FATA[0000] newuidmap not found (install uidmap package?): exec: "newuidmap": executable file not found in $PATH·
=> check for newuidmap before reexec

Dockerfile
Applies https://github.com/shadow-maint/shadow/pull/132 so that we
don't need to have CAP_SYS_ADMIN.
See also https://github.com/genuinetools/img/issues/170 .
=> use Giuseppe's forked newuidmap/newgidmap

Dockerfile
I've done few changes and pushed a new version so the old commit
doesn't exist anymore.  Since I am probably going to make more
changes, it is safer to use the branch.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> Dockerfile, shadow: use the branch name instead of the commit

README.md
It now matches the sha256sum that is on the release page.
=> Changed the sha256sum in the readme

Dockerfile
shadow-maint/shadow#138 caused a regression reported in
genuinetools/img#191.
Temporarily fork shadow again until shadow-maint/shadow#141 gets merged.
@jessfraz @giuseppe
=> Fork shadow again temporarily

.travis.yml
Hi 👋, I was checking out `img` and it seems cool so I thought I'd try make a super minor contribution.
This updates Travis to use the Xenial environment, which Travis reckons is now ["ready for a wider audience"](https://blog.travis-ci.com/2018-11-08-xenial-release). This makes using `trusty-backports` unnecessary.
Other _very_ minor changes:
* `sudo: true` is now unnecessary. All Travis builds have sudo now.
* Moved the deploy debug message to `before_deploy` which only gets run if `deploy` will be. Alternatively, could skip the build stage completely if there is no tag, but that'd mean `make release` would be run much less often.
=> Travis: Use xenial build dist + tiny cleanup

README.md
The the alpine package is in the edge/testing repository, so running:
```console
apk add img
```
won't work by default, hence the update to:
```console
apk add img --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
```
=> Added apk repository url.

README.md
Hey there. Thanks for a great project! Since the `--platform` flag was just merged to master I had some fun playing around with it. It's really nice!
I had a little trouble cobbling the information together that I needed to get running, so I added some documentation for it to help future users.
I am happy to make any changes suggested, if there is a better place to put this documentation just let me know.
Thanks again!
=> Add documentation for platform build

Makefile
This enables a Go-native os/user which should make binaries built on
Ubuntu Bionic (in this case, via travis-ci.org) work on other Linuxes
with different syscall ABIs.
Fixes a segfault when cgo is looking up a user.
=> Add osusergo build tag

login.go
For img login the username can be passed via -u or --user but --user is not compatible with docker cli. So changing it to --username to be same as docker cli. It was --username before the last release. Reverting back to same.
=> Changing the long form for username in img login to be username instead of user

README.md, build.go, client/controller.go, go.mod, go.sum, vendor/github.com/moby/buildkit/cache/contenthash/filehash.go, vendor/github.com/moby/buildkit/cache/contenthash/tarsum.go, vendor/github.com/moby/buildkit/cache/refs.go, vendor/github.com/moby/buildkit/cache/remotecache/inline/inline.go, vendor/github.com/moby/buildkit/cache/remotecache/local/local.go, vendor/github.com/moby/buildkit/cache/remotecache/v1/cachestorage.go, vendor/github.com/moby/buildkit/cache/remotecache/v1/chains.go, vendor/github.com/moby/buildkit/frontend/gateway/gateway.go, vendor/github.com/moby/buildkit/frontend/gateway/pb/caps.go, vendor/github.com/moby/buildkit/session/filesync/filesync.go, vendor/github.com/moby/buildkit/solver/edge.go, vendor/github.com/moby/buildkit/solver/llbsolver/file/backend.go, vendor/github.com/moby/buildkit/util/contentutil/pusher.go, vendor/github.com/moby/buildkit/util/push/push.go, vendor/modules.txt
Added in support to utilize moby/buildkit `import-cache` and `export-cache` fields. Updated the README to include all the information about the new fields. Thanks to @Chippiewill for all the help that he did through his #279 PR, really made this addition a lot easier. This is to support #263 and all to add the ability to utilize more caching by being able to export some cache! Also thanks to #287, helped me understand more by providing a better explanation for the README.
Let me know if anything needs changes! First time committing in this repo, so please be kind especially if I made any silly mistakes.
=> Cache import/export support

client/prune.go
The current implementation of `img prune` does not actually remove any data. This changeset introduces an extra variadic argument to the `Prune` call, producing behavior equivalent to `buildctl prune` invoked without flags against a BuildKit daemon.
I think the issue and proposed fix become more clear with a look at the underlying implementation, which loops over the variadic
`PruneInfo` arguments and runs a prune operation based on options specified in each argument. With no arguments, it skips the loop and only runs the final garbage collection on the metadata store.
https://github.com/genuinetools/img/blob/d858ac71f93cc5084edd2ba2d425b90234cf2ead/vendor/github.com/moby/buildkit/cache/manager.go#L515-L520
I believe this resolves #153 and resolves #320.
=> Fix "prune" subcommand

client/inspect.go, inspect.go, inspect_test.go, main.go
This CLI mimics `docker inspect`: it will print the OCI image config to
stdout as raw JSON. This can be used with `jq` or other tools to extract
useful metadata about an image.
Similar to `img pull`, `img inspect` only takes _one_ image (unlike
`docker inspect` which can take multiple and outputs an array). I felt
it was more important to act like img than it was to act like Docker.
Tests included.
As for **why?** We're using `img` to do daemonless Docker builds but
we need to do post-build inspection on the image. We used the Docker
API previously for this (`InspectImageWithRaw`) but `img` provides not
alternative for us. It'd be great to have this information.
Example:
(Note that the fact entrypoints and other stuff aren't visible in the above is showing the bug of #199 but that's …
=> `img inspect` command: dump the JSON for the image config to stdout

client/pull.go, pull_test.go
Fixes #199 
Related to #234 
Previously `pull` would not properly retain the image configuration
which contains the entrypoint, working directory, user, and more. This
resulted in broken images if they were pulled then subsequently pushed.
This commit fetches the image config, which must be done separately, and
then ensures that the configuration is set on the exported image into
the local img state store.
Note that the config that is stored is an OCI image config and NOT a 
Docker config so the digest is still not equivalent but the encoding of this
is in BuildKit and not img so I think this is fine.
=> pull: resolve the image config and set it on stored image
