- Dockerfile
- README.md
1m12s -> 1m0s (with overlay backend)
> Dockerfile: multistage

- .travis.yml
- build.go
- build_test.go
- login.go
- main.go
- main_test.go
- pull_test.go
Handle piping build context from stdin.
Closes #27
Updates #10
Testing travis.
> Add tests.

- README.md
> add note about building from source on Linux

- README.md
- main.go
- save.go
- util/dockerexporter/REMOVEME
- util/dockerexporter/dockerexporter.go
> support exporting an image to Docker

- .travis.yml
- README.md
- main_test.go
use a version of runc with patches
cc @AkihiroSuda
> remove sudo from tests

- executor/runc/executor.go
just for easier tracking
cc @AkihiroSuda
> update code comments

- build.go
- build_test.go
- testdata/Dockerfile.test-build-dockerfile-not-in-context
- utils.go
> Set default dockerfile path and send the base to the controller as filename

- client/remove.go
- main.go
- remove.go
Should be noted that this command does not remove layers from cache. Is it okay?
> Implement 'rm' command to remove images

- push.go
> Add missing newline to the message in 'push' command

- exporter/containerimage/writer.go
> Fixes a trivial logging typo

- README.md
> Typo: snaphotter to snapshotter

- README.md
Adds a reference to the great new blog post regarding building images securely using img on k8s
> Reference to recent blog post

- README.md
> Document dependency on execv & newuidmap

- README.md
> README.md: update for rootless mode

- build_test.go
> add TestBuildApt

- Makefile
> minor update makefile

- .gitignore
Signed-off-by: Noel Georgi <18496730+frezbo@users.noreply.github.com>
> git ignoring direnv files to support per folder vars like IMG_DISABLE_EMBEDDED_RUNC

- README.md
Update readme to include --label flag for img build for #168
> update readme with --label flag for img build

- README.md
- build.go
- build_test.go
Support multi-tagging with `img build` per #150
> Support multiple tags being passed with img build

- Dockerfile
> unfork newuidmap/newgidmap

- build.go
> implement --no-cache

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/cache/contenthash/checksum.go
- vendor/github.com/moby/buildkit/client/llb/source.go
- vendor/github.com/moby/buildkit/client/llb/state.go
- vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
- vendor/github.com/moby/buildkit/frontend/dockerfile/shell/lex.go
- vendor/modules.txt
> bump up BuildKit to v0.3.2 (support CoreOS)

- Dockerfile
> unfork shadow again

- Makefile
Closes: https://github.com/genuinetools/img/issues/238
> Specify default buildtags as optional

- README.md
Adding the answer from #266  to the README
> Add clarification on how to run in kubernetes as unprivileged

- README.md
Bug: https://github.com/genuinetools/img/issues/292
> Drop --repository flag for Alpine

- README.md
fix img login option --username for img login
> Fix readme img login --username option
